In [27]:
# Import the numpy package under the name np
import numpy as np

# Create a null vector of size 10
a = np.zeros(10)

# Create a vector with values ranging from 10 to 49
b = np.arange(10,49)

# Find the shape of previous array in question 3
b.shape

# Print the type of the previous array in question 3
print(b.dtype)

# Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

# Print the dimension of the array in question 3
print(b.ndim)

# Create a boolean array with all the True values
c = np.full((2,2),True)


int32
1.13.1
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Program Files/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Program Files/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Program Files/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Program Files/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_d

# Creating Arrays

In [42]:
# Create a two dimensional array
d = np.array([[3,2,1],[4,8,6]])

# Create a three dimensional array
e = np.array([[[9,3,5],[6,3,9]],[[7,8,9],[13,11,10]]])

# Diaognal Matrix
print("Diaognal Matrix: ",np.eye(5))

# Array with all values 1
print("Matrix with all ones: ",np.ones((3,4)))

# Array with all values 0
print("Matrix with all zeros: ",np.zeros((3,4)))

# Array of 6 evenly divided values from 0 to 100
print("Evenly divided values: ",np.linspace(0,100,6))

# Array of values from 0 to less than 10 with step 3 
print("arange Function with step 3: ",np.arange(0,10,3))

#  2x3 array with all values 8
print("Full Function: ",np.full((2,3),8))

# 4x5 array of random floats between 0–1
print("array of random floats between 0–1: ",np.random.rand(4,5))

# 6x7 array of random floats between 0–100
print("array of random floats between 0–100: ",np.random.rand(6,7)*100)

# 2x3 array with random ints between 0–4
print("array with random ints between 0–4: ", np.random.randint(5,size=(2,3)))

Diaognal Matrix:  [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
Matrix with all ones:  [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
Matrix with all zeros:  [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Evenly divided values:  [   0.   20.   40.   60.   80.  100.]
arange Function with step 3:  [0 3 6 9]
Full Function:  [[8 8 8]
 [8 8 8]]
array of random floats between 0–1:  [[  1.23907456e-01   7.85798711e-01   2.59912274e-01   8.54831746e-01
    6.65360859e-01]
 [  5.03236731e-02   6.88061513e-01   6.43508674e-01   4.25730596e-01
    4.08306599e-01]
 [  4.57639182e-01   7.78730054e-01   1.59553515e-01   4.90874859e-01
    7.78219900e-01]
 [  4.30532017e-01   4.77868122e-01   7.34516781e-04   3.76545006e-01
    7.11075190e-01]]
array of random floats between 0–100:  [[ 62.81052423  38.83028145  15.32326647  42.56084866  50.89669679
   46.41555731   8.62755214]
 [ 23.10501613  17.51248816  82.2

# Inspecting Properties

In [24]:
arr = np.arange(10,48)
print("Array ",arr)

# Returns number of elements in arr
print("number of elements in arr ", arr.size)

# Returns dimensions of arr (rows,columns)
print("dimensions of arr ", arr.shape)

# Returns type of elements in arr
print("type of elements in arr ", arr.dtype)

# Convert arr elements to type dtype
print("Convert arr elements to type dtype ",arr.astype(float))

# Convert arr to a Python list
print("arr to a Python list: ",arr.tolist())

# View documentation for np.eye
np.info(np.eye)

Array  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47]
number of elements in arr  38
dimensions of arr  (38,)
type of elements in arr  int32
Convert arr elements to type dtype  [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.
  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.
  40.  41.  42.  43.  44.  45.  46.  47.]
arr to a Python list:  [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
 eye(N, M=None, k=0, dtype=<class 'float'>)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diago

# Copying/sorting/reshaping

In [54]:
# Copies arr to new memory
print("Copies arr to new memory: ",np.copy(arr))

# Creates view of arr elements with type dtype
print("view of arr elements with type dtype: ",arr.view(int))

# Sorts array
d.sort()

# Sorts specific axis of arr
e.sort(axis=0)

# Flattens 2D array to 1D
d.flatten()


# Transposes array (rows become columns and vice versa)
d.T

# Reshapes arr to 3 rows, 4 columns without changing data
e.reshape(3,4)

# Changes arr shape to 5x6 and fills new values with 0
arr.resize((5,6))


Copies arr to new memory:  [[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]
view of arr elements with type dtype:  [[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]


# Adding/removing Elements

In [57]:
#  Appends values to end of arr
np.append([[0, 1, 2], [3, 4, 5]],[[6, 7, 8]], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
# Inserts values into arr before index 2
x = np.array([[0,0], [1,1], [2,2]])
np.insert(x,2,4)


array([0, 0, 4, 1, 1, 2, 2])

In [59]:
np.insert(x,2,4,axis=1)

array([[0, 0, 4],
       [1, 1, 4],
       [2, 2, 4]])

In [60]:
# Deletes row on index 1 of arr
arr = np.array([[0,1,2], [4,5,6], [7,8,9]])
arr

array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.delete(arr, 1, 0)

array([[0, 1, 2],
       [7, 8, 9]])

In [62]:
# Deletes column on index 2 of arr
arr = np.array([[0,1,2], [4,5,6], [7,8,9]])
arr

array([[0, 1, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.delete(arr,2,1)

array([[0, 1],
       [4, 5],
       [7, 8]])

# Combining/splitting

In [65]:
# Adds arr2 as rows to the end of arr1
arr1 = np.array([[3, 4], [5, 6]])
arr2 = np.array([[7, 8]])
np.concatenate((arr1,arr2), axis=0)

array([[3, 4],
       [5, 6],
       [7, 8]])

In [69]:
# Adds arr2 as columns to end of arr1

np.concatenate((arr1,arr2.T), axis=1)

array([[3, 4, 7],
       [5, 6, 8]])

In [70]:
# Splits arr into 3 sub-arrays
np.split(arr,3)

[array([[0, 1, 2]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [73]:
#  Splits arr horizontally on the 5th index
np.hsplit(e,2)

[array([[[7, 3, 5]],
 
        [[9, 8, 9]]]), array([[[ 6,  3,  9]],
 
        [[13, 11, 10]]])]

# Indexing/slicing/subsetting

In [74]:
# Returns the element at index 2
arr[2]

array([7, 8, 9])

In [76]:
# Returns the 2D array element on index [1][2]
d[1,2]

8

In [80]:
# Assigns array element on index 1 the value 4
arr[1]=60

In [86]:
# Assigns array element on index [1][3] the value 10
d[1,2]=10

In [87]:
# Returns the elements at indices 0,1,2 (On a 2D array: returns rows 0,1,2)
d[0:3]

array([[ 1,  2,  3],
       [ 4,  6, 10]])

In [89]:
# Returns the elements on rows
d[0:1,2]

array([3])

In [90]:
# Returns the elements at indices 0,1 (On a 2D array: returns rows 0,1)
arr[:2]

array([[ 0,  1,  2],
       [60, 60, 60]])

In [91]:
# Returns the elements at index 1 on all rows
arr[:,1]

array([ 1, 60,  8])

In [92]:
# Returns an array with boolean values
arr<5

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [93]:
# Returns an array with boolean values
(arr1<3) & (arr2>5)

array([[False, False],
       [False, False]], dtype=bool)

In [94]:
#  Inverts a boolean array
~arr

array([[ -1,  -2,  -3],
       [-61, -61, -61],
       [ -8,  -9, -10]], dtype=int32)

In [95]:
# Returns array elements smaller than 5
arr[arr<5]

array([0, 1, 2])

# Statistics 

In [96]:
# Returns mean along specific axis
np.mean(arr,axis=0)

array([ 22.33333333,  23.        ,  23.66666667])

In [97]:
# Returns sum of arr
arr.sum()

207

In [98]:
# Returns minimum value of arr
arr.min()

0

In [99]:
# Returns maximum value of specific axis
arr.max(axis=0)

array([60, 60, 60])

In [100]:
# Returns the variance of array
np.var(arr)

693.11111111111109

In [102]:
#  Returns the standard deviation of specific axis
np.std(arr,axis=1)

array([ 0.81649658,  0.        ,  0.81649658])

# Vector Math

In [106]:
# Elementwise add arr2 to arr1
np.add(arr1,arr2)

array([[10, 12],
       [12, 14]])

In [107]:
# Elementwise subtract arr2 from arr1
np.subtract(arr1,arr2)

array([[-4, -4],
       [-2, -2]])

In [108]:
# Elementwise multiply arr1 by arr2
np.multiply(arr1,arr2)

array([[21, 32],
       [35, 48]])

In [109]:
#  Elementwise divide arr1 by arr2
np.divide(arr1,arr2)

array([[ 0.42857143,  0.5       ],
       [ 0.71428571,  0.75      ]])

In [110]:
# Elementwise raise arr1 raised to the power of arr2
np.power(arr1,arr2)

array([[   2187,   65536],
       [  78125, 1679616]], dtype=int32)

In [111]:
# Returns True if the arrays have the same elements
np.array_equal(arr1,arr2)

False

In [112]:
# Square root of each element in the array
np.sqrt(arr)

array([[ 0.        ,  1.        ,  1.41421356],
       [ 7.74596669,  7.74596669,  7.74596669],
       [ 2.64575131,  2.82842712,  3.        ]])

In [113]:
# Sine of each element in the array
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743],
       [-0.30481062, -0.30481062, -0.30481062],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [115]:
# Natural log of each element in the array
np.log(arr1)

array([[ 1.09861229,  1.38629436],
       [ 1.60943791,  1.79175947]])

In [116]:
# Absolute value of each element in the array
np.abs(arr)

array([[ 0,  1,  2],
       [60, 60, 60],
       [ 7,  8,  9]])

In [117]:
# Rounds up to the nearest int
np.ceil(arr)

array([[  0.,   1.,   2.],
       [ 60.,  60.,  60.],
       [  7.,   8.,   9.]])

In [118]:
#  Rounds down to the nearest int
np.floor(arr)

array([[  0.,   1.,   2.],
       [ 60.,  60.,  60.],
       [  7.,   8.,   9.]])

In [119]:
# Rounds to the nearest int
np.round(arr)

array([[ 0,  1,  2],
       [60, 60, 60],
       [ 7,  8,  9]])

# Scalar Math

In [120]:
# Add 1 to each array element
np.add(arr,1)

array([[ 1,  2,  3],
       [61, 61, 61],
       [ 8,  9, 10]])

In [121]:
# Subtract 2 from each array element
np.subtract(arr,2)

array([[-2, -1,  0],
       [58, 58, 58],
       [ 5,  6,  7]])

In [122]:
# Multiply each array element by 3
np.multiply(arr,3)

array([[  0,   3,   6],
       [180, 180, 180],
       [ 21,  24,  27]])

In [123]:
# Divide each array element by 4 (returns np.nan for division by zero)
np.divide(arr,4)

array([[  0.  ,   0.25,   0.5 ],
       [ 15.  ,  15.  ,  15.  ],
       [  1.75,   2.  ,   2.25]])

In [124]:
# Raise each array element to the 5th power
np.power(arr,5)

array([[        0,         1,        32],
       [777600000, 777600000, 777600000],
       [    16807,     32768,     59049]], dtype=int32)